---
- name: install curl
  apt:
    name: "{{ pkgs }}"
    update_cache: yes
    state: present
  with_items: "{{ pkgs }}"

- name: install croc
  shell: curl https://getcroc.schollz.com | bash
  args:
    warn: no
